### ISSUE TITLE
导航组件没有声音

### ISSUE THREAD

**Issue by Spicely** [laoqiu/flutter-amap-view#2]
![image](https://user-images.githubusercontent.com/10075622/81479382-6efa6300-9255-11ea-8aa7-8af611a339bb.png)
 调整音量一直这个

**Comment by Spicely** [comment]
调试没有 正式包正常 并不影响

**Comment by laoqiu** [comment]
我还没来得及看，就解决了，有其他问题记得提，有什么功能要加也可以说

发自我的iPhone

**Comment by Spicely** [comment]
导航组件在Ios上闪退 
尝试升级到最新版
修改 MAMapKit 为 AMapNaviKit
导航组件报如下错误 [已解决]
![image](https://user-images.githubusercontent.com/10075622/81495188-09ec4f00-92e1-11ea-9de7-f08dd01a07b4.png)
需要在info.plist 下增加
`<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>`

导航有直接进行导航的方法么
