### ISSUE TITLE
导航功能 骑行和步行不能正常使用

### ISSUE THREAD

**Issue by Spicely** [laoqiu/flutter-amap-view#3]
查看源码是使用的高德导航组件 但这功能 并未提供
有考虑实现么

**Comment by laoqiu** [comment]
我今天看看

发自我的iPhone

**Comment by laoqiu** [comment]
RouteNavi({this.naviType = NaviType.driver, this.start, @required this.end, this.wayList})

enum NaviType {
  // 驾车
  driver,

  // 步行
  walk,

  // 骑行
  ride,
}

我记得是有的，你试试传入不同参数。
主要是自己用用，example没写全，等空了补上

**Comment by Spicely** [comment]
> RouteNavi({this.naviType = NaviType.driver, this.start, @required this.end, this.wayList})
> 
> enum NaviType {
> // 驾车
> driver,
> 
> // 步行
> walk,
> 
> // 骑行
> ride,
> }

这个我看了的 在android 使用 骑行和步行在开始页面没有路线 一直是北京 进入导航后只有声音没有绘制线路
在IOS直接启动的驾车
版本 为最新sdk 使用老版本缺少更多

**Comment by laoqiu** [comment]
哦。这样，android用的是真机调试吗？
ios上导航组件只支持驾车和货车，要支持需要重新写了，不能直接用导航组件。
https://lbs.amap.com/api/ios-navi-sdk/guide/navigation-map/gps
不难，你可以自己试着实现一下

**Comment by Spicely** [comment]
都是真机调试
对  导航组件都不支持这两个

你能提供一个初始框架么 主要我不是搞android 和 ios的 

里面内容我这边来填写

**Comment by laoqiu** [comment]
dart层基本上不需要动，只需要改下android的AmapNaviFactory.kt文件和iOS的AmapNavFactory.swift文件

晚上我回家更新一下吧

**Comment by Spicely** [comment]
好的 谢谢

**Comment by Spicely** [comment]
请问 单次获取定位如何写?

**Comment by laoqiu** [comment]
单次定位给你加了个参数
>     await AmapLocation.start(once: true); // 单次定位
这个导航不用组件要自己写view，我在android那打了个注释，只能计算路线，好久没跑了，依赖都加载不了，android studio无法加载flutter sdk了，改天再弄了

**Comment by Spicely** [comment]
好的 有注释也行 我尝试下编写

**Comment by Spicely** [comment]
已完成计算路线 我该如何显示显示view?

**Comment by Spicely** [comment]
目前已完成跳转native页面 但只有声音 视图一片黑 能帮忙看下么

**Comment by laoqiu** [comment]
额。我也没经验，都是边学边写，最近没时间研究

发自我的iPhone

**Comment by Spicely** [comment]
android导航 已经完成 现在编写ios 我无法跳转IOS的native页面 能指点下么

**Comment by laoqiu** [comment]
有什么异常吗？

发自我的iPhone

**Comment by Spicely** [comment]
![image](https://user-images.githubusercontent.com/10075622/81890097-b7a87800-95d7-11ea-9fb0-9e4d60ee0221.png)
直接获取rootViewController 显示 为nil
![image](https://user-images.githubusercontent.com/10075622/81890181-ec1c3400-95d7-11ea-8117-418fd545a6c6.png)
修改 继承 在运行时报错
![image](https://user-images.githubusercontent.com/10075622/81890221-0524e500-95d8-11ea-875a-f7a004e58b14.png)

**Comment by Spicely** [comment]
目前IOS骑行、步行 导航能正常跳转 但跳转后会导致监听失效 我该如何修改
